services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./commentaires.json:/opt/commentaires.json
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
    driver: local
